version: '3.9'

services:
    app:
        build: .
        container_name: laravel_app
        ports:
            - "8000:8000"
            - "5173:5173" # Vite default port
        volumes:
            - .:/var/www/html
        environment:
            APP_ENV: local
            APP_DEBUG: 'true'
            APP_KEY: base64:somekey
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
            YOUTUBE_API_KEY:
            PLAYLIST_ID:
